service: nest-serverless-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: production
    ORDER_QUEUE_URL: !Ref OrderQueue

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt OrderQueue.Arn

functions:
  handleQueueMessage:
    handler: dist/lambda.handler
    events:
      - sqs:
          arn: !GetAtt OrderQueue.Arn
          batchSize: 1

resources:
  Resources:
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: nest-serverless-app-process-order-queue

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude: []
    target: node18
    platform: node
    concurrency: 10
